# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "multipart-post", "~> 2.4"

gem "bundle", "~> 0.0.1"
gem "add", "~> 0.3.2"
gem "net-http", "~> 0.6.0"

gem "rqrcode", "~> 3.1"

gem "mime-types", "~> 3.7"
